name: Compiling Rconnect on Github Actions
on: [push]
jobs:
  compile-rconnect:
    runs-on: ubuntu-latest
    steps:
      - uses: rsksmart/rconnect@master
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
