name: Compiling Rconnect on Github Actions
on: [push]
jobs:
  compile-rconnect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rsksmart/rconnect
          ref: master
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
