name: Compiling Light Client SDK on Github Actions
on: [push]
jobs:
  compile-rconnect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - uses: actions/checkout@v2
        with:
          repository: rsksmart/lumino-light-client-sdk
          ref: master
      - run: npm install
      - run: npm run build
